name: example-github-actions-run
on: [push]
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "Hello"
          ls -la
          ./a.sh
